#!/usr/bin/env python3

#####################################################################
######################## Import Packages ############################
#####################################################################

import time
start_time = time.time()
import Functions as f

#####################################################################
########################## Calculations #############################
#####################################################################

N=300

#Flux Parameters
# Emt=0.38       #Max thermal energy in ev
# Eme=1e5        #Max epithermal energy in ev
# E0=0.0658       #Thermal average in ev (1045 K)
# Ef=1.35e6      #Fission average in ev
Emt=[0.5]
Eme=[1E5]
E0=[0.09]
Ef=[1.35E6]
    
#Set energy, in ev
E=f.np.logspace(-5,8,N)  #Whole Range
Ethermal=f.np.logspace(-5,0,int(N/3)) #Thermal
Eepi=f.np.logspace(0,5,int(N/3))
Efast=f.np.logspace(5,8,int(N/3))

C=[0.4865]
a=[0.966,1,1.17]
#a=[1]
b=[1.461,2,3.4005]
#b=[2]

#f.VaryChi(E,C,a,b)
#f.VaryPhi(E,Emt,Eme,E0,Ef)

f.PlotChiNPhi(E,Emt[0],Eme[0],E0[0],Ef[0],C[0],a[0],b[0])

#f.PercentChi(C[0],a[0],b[0],E,Ethermal,Eepi,Efast)



##################################################################
######################## Time to Execute #########################
##################################################################

print("--- %s seconds ---" % (time.time() - start_time))
