#!/usr/bin/env python3
"""
This program will compute 1-group cross sections with a weighted 
flux. Parameters for the flux were
determined in a subdirectory called Reduce_Err. 
"""

#####################################################################
######################## Import Packages ############################
#####################################################################

import time
start_time = time.time()
import Functions as f
from scipy import interpolate
from scipy import integrate
from scipy.integrate import trapz

#####################################################################
########################## Calculations #############################
#####################################################################

#Flux Parameters
# Emt=0.38       #Max thermal energy in ev
# Eme=1e5        #Max epithermal energy in ev
# E0=0.0658       #Thermal average in ev (1045 K)
# Ef=1.35e6      #Fission average in ev
Emt=[0.5]
Eme=[1E5]
E0=[0.09]
Ef=[1.35E6]
    
#Set energy, and convert from MeV to ev
E=f.np.logspace(-5,8,300)    

C=[0.4865]
a=[0.966,1,1.17]
#a=[1]
b=[1.461,2,3.4005]
#b=[2]

f.VaryChi(E,C,a,b)
f.VaryPhi(E,Emt,Eme,E0,Ef)



##################################################################
######################## Time to Execute #########################
##################################################################

print("--- %s seconds ---" % (time.time() - start_time))
